### ISSUE TITLE
Typings for setValue and patchValue

### ISSUE THREAD

**Issue by ramarivera** [no0x9d/ngx-strongly-typed-forms#11]
The signature of the patchValue method is:

`patchValue(value: Partial<T>, options?: {
        onlySelf?: boolean;
        emitEvent?: boolean;
}): void;`

while for the setValue method:

`setValue(value: {
        [key: string]: any;
    }, options?: {
        onlySelf?: boolean;
        emitEvent?: boolean;
 }): void;`

Since the `patchValue` is a `Partial<T>`, shouldn't the `setValue` take a value of type `T`? Or is there something I am missing regarding `setValue`?

Thanks!

**Comment by no0x9d** [comment]
fixed with #20
