### ISSUE TITLE
Cannot find module '@angular/forms/src/model'.

### ISSUE THREAD

**Issue by RyannGalea** [no0x9d/ngx-strongly-typed-forms#12]
Hey guys, 

Any idea how I can resolve this issue:
- Using angular 8.0.0

`ERROR in node_modules/ngx-strongly-typed-forms/model.d.ts(2,27): error TS2307: Cannot find module '@angular/forms/src/model'.`

I changed the typing related to 'FormHooks' to 'any' inside of model.d.ts to allow me to continue working on the project but it obviously is not the correct fix.

**Comment by Rockstar311** [comment]
Yes, the same problem can't update my project to Angular 8 through this package

**Comment by hamzaabamboo** [comment]
I believed that FormHooks was not exported from @angular/forms.
```ts
declare type FormHooks = 'change' | 'blur' | 'submit';
```

**Comment by no0x9d** [comment]
Yes, I used an internal declaration of FormHooks which was removed.
In the new version 8.0.1 i declare FormHooks myself. I hope this should solve the problem.
