### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by sserdyuk** [no0x9d/ngx-strongly-typed-forms#16]
@no0x9d  I just want to say thank you for putting this plugin out here. Angular's lack of typed forms is surprising, and your plugin is very helpful. I hope you continue updating it as your schedule permits.

**Comment by no0x9d** [comment]
Thank you for your kind comment. I really appreciate it. 
I'm happy that the things I created for my own project is helping others as well.
I'll try to stay up to date with Angular as much as I can and I'm always open for contributions
