### ISSUE TITLE
Doesn't build with rxjs 6.x, requires rxjs-compat to be installed

### ISSUE THREAD

**Issue by CyberBotX** [no0x9d/ngx-strongly-typed-forms#2]
If rxjs-compat is not installed while rxjs 6.x is installed, the following error occurs when building an Angular project using ngx-strongly-typed-forms with the Angular CLI for AOT:

```
ERROR in node_modules/rxjs/Observable.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/Observable'.
node_modules/ngx-strongly-typed-forms/model.d.ts(3,9): error TS2305: Module '"/www/www/angular/node_modules/rxjs/Observable"' has no exported member 'Observable'.
```

While this is solved by installed rxjs-compat, ngx-strongly-typed-forms should be updated to work with rxjs 6.x. I am unsure if that can be done in a way to allow it to work with pre-rxjs 6.x projects or not, though.

**Comment by no0x9d** [comment]
Imports are fixed in v0.10.0. 
This version should also support Angular 5 and 6.
