### ISSUE TITLE
AOT build Issue

### ISSUE THREAD

**Issue by dhruvb14** [no0x9d/ngx-strongly-typed-forms#6]
When executing production build using following command: 
`ng build --extract-css "--prod"`

while using angular 6.1 latest build I am getting a error: 

`ERROR in : Unexpected value 'NgxStronglyTypedFormsModule in E:/dev/Application/Application.Web/ClientApp/node_modules/ngx-strongly-typed-forms/module.d.ts' imported by the module 'AppModule in E:/dev/Application/Application.Web/ClientApp/src/app/app.module.ts'. Please add a @NgModule annotation.`

**app.module.ts**

`// Angular
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { Routes, RouterModule } from '@angular/router';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { ReactiveFormsModule } from '@angular/forms';
import { NgxStronglyTypedFormsModule } from 'ngx-strongly-typed-forms';

// Vendor
import { AngularFontAwesomeModule } from 'angular-font-awesome';

// Modules
import { CoreModule } from './core/core.module';
import { SharedModule } from './shared/shared.module';

import { ToasterModule, ToasterService } from 'angular2-toaster';

// Components
import { AppComponent } from './app.component';
import { HomeComponent } from './home/home.component';
// Import the ButtonsModule
import { FormBuilder } from 'ngx-strongly-typed-forms';

@NgModule({
    declarations: [
        AppComponent,
        HomeComponent
    ],
    imports: [
        NgxStronglyTypedFormsModule,
        CoreModule,
        BrowserModule,
        ReactiveFormsModule,
        SharedModule,
        RouterModule.forRoot([
            {
                path: '',
                redirectTo: 'home', pathMatch: 'full'
            },
            {
                path: 'home',
                component: HomeComponent
            }
        ], { useHash: true , enableTracing: false}),
        BrowserAnimationsModule,
        ToasterModule.forRoot()
    ],
    exports: [RouterModule],
    providers: [FormBuilder],
    bootstrap: [AppComponent]
})
export class AppModule { }`

**Application runs fine without the prod flag but fails otherwise. I assume its related to AOT**

**Comment by no0x9d** [comment]
Please tell me which version you use. There are known problems with the AOT build the the import of NgxStronglyTypedFormsModule.

As workaround you remove the import of the NgxStronglyTypedFormsModule. You already provide the FormBuilder yourself so no other change must be made. I will look into this error.

**Comment by no0x9d** [comment]
Please try the new version 1.0.0-rc5, which should fix the problem.
You also don't have to provide the FormBuilder anymore, when you import the NgxStronglyTypedFormsModule
