### ISSUE TITLE
Can't resolve 'ngx-strongly-typed-forms/model' when doing prod build

### ISSUE THREAD

**Issue by jaufgang** [no0x9d/ngx-strongly-typed-forms#7]
When doing an angular build with the `--prod` flag, a series of errors like the one below show up wherever I import `FormBuilder`
```
ERROR in ./src/app/app.module.ngfactory.js
Module not found: Error: Can't resolve 'ngx-strongly-typed-forms/model' 
```

**Comment by no0x9d** [comment]
There is a problem with the AOT build in the current rc version. This version was published under the latest tag by mistake.
Please use the version 0.10.0 for now, while I try to fix the bug

**Comment by no0x9d** [comment]
There was a problem with the generated metadata for aot builds.
Please try the new version 1.0.0-rc5, which should fix the problem.

When everything works, this version will become v1.0.0 after documentation updates.

**Comment by jaufgang** [comment]
`1.0.0-rc5` works well.  Thanks!
